#[[remove]]
#directory = "target/"

[[remove]]
directory = "src/"

[[remove]]
directory = "app/"

[[remove]]
directory = "test/"

[[remove]]
directory = "target/Target/AntiPattern/"

[[remove]]
file = "target/Target/AntiPattern.hs"

[[remove]]
file = "target/Target/Partial.hs"

[[remove]]
file = "target/Target/Infinite.hs"

[[remove]]
file = "target/Target/Style.hs"

[[check]]
type = "Exclude"
directory = "test/"
id = "STAN-0208"

[[check]]
type = "Exclude"
file = "src/Stan/Cabal.hs"
id = "STAN-0212"

[[check]]
type = "Exclude"
file = "src/Stan/Example.hs"
filter = "all"
