#!/usr/bin/env bash
#
###############################################################################
# NOTICE: THIS SCRIPT WAS FULLY GENERATED BY AN LLM.
#
#   Generator: Claude (Anthropic), model "claude-opus-4-8".
#
#   It is provided AS-IS, WITHOUT WARRANTY OF ANY KIND, and MAY CONTAIN BUGS
#   OR SECURITY RISKS.
#
#   This script performs PRIVILEGED ACTIONS. It:
#     * uses `sudo`,
#     * downloads source code from the internet (git),
#     * compiles that source code,
#     * installs libraries into system directories (default /usr/local),
#     * creates symlinks in the system pkg-config directory, and
#     * writes to /etc/ld.so.conf.d.
#
#   REVIEW THIS SCRIPT and make sure you understand what it does BEFORE you
#   run it. You run it AT YOUR OWN RISK.
###############################################################################
#
# install-system-deps.sh
#
# Installs the native system libraries required to build the plutus/cardano
# test fixtures used by plu-stan:
#
#   * libsodium  (IntersectMBO/VRF fork) -> pkg-config name: libsodium
#   * secp256k1  (with schnorrsig)       -> pkg-config name: libsecp256k1
#   * blst       (BLS12-381)             -> pkg-config name: libblst
#
# Without these, `cabal build all` fails on Linux with e.g.
#   "pkg-config package libblst-any, not found".
#
# Canonical pins (the widely-used cardano-node/IOG values):
#   libsodium: https://github.com/intersectmbo/libsodium
#              commit dbb48cce5429cb6585c9034f002568964f1ce567 (VRF fork)
#   secp256k1: https://github.com/bitcoin-core/secp256k1  tag v0.3.2
#   blst:      https://github.com/supranational/blst      tag v0.3.11
#
# The script is idempotent: for each library it first checks
# `pkg-config --exists <name>` and skips the build if already satisfied.
#
# Everything installs to $PREFIX (default /usr/local) on both macOS and Linux.
# You can override with:  PREFIX=/some/where bash scripts/install-system-deps.sh
#
# NOTE: installing libraries needs write access to $PREFIX, so `sudo` is used
# for the install step when you are not root.
#
set -euo pipefail

# ----------------------------------------------------------------------------
# Configuration / pins
# ----------------------------------------------------------------------------
PREFIX="${PREFIX:-/usr/local}"

LIBSODIUM_REPO="https://github.com/intersectmbo/libsodium"
LIBSODIUM_REF="dbb48cce5429cb6585c9034f002568964f1ce567"

SECP256K1_REPO="https://github.com/bitcoin-core/secp256k1"
SECP256K1_REF="v0.3.2"

BLST_REPO="https://github.com/supranational/blst"
BLST_REF="v0.3.11"
BLST_VERSION="0.3.11"

WORKDIR="${TMPDIR:-/tmp}/plu-stan-syslibs"

# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
info() { printf '    %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# Run a command as root when we are not already root.
SUDO=""
maybe_sudo() {
  if [ "$(id -u)" -eq 0 ]; then
    "$@"
  else
    ${SUDO:-sudo} "$@"
  fi
}

have() { command -v "$1" >/dev/null 2>&1; }

# Is $1 present as an element of the colon-separated list $2 ?
path_contains() {
  local needle="$1" list="$2" old_ifs="$IFS" el
  IFS=':'
  for el in $list; do
    if [ "$el" = "$needle" ]; then IFS="$old_ifs"; return 0; fi
  done
  IFS="$old_ifs"
  return 1
}

# Print the first element of the colon-separated list $1 that is an existing
# directory. Returns nonzero (and prints nothing) if none exist.
first_existing_dir() {
  local list="$1" old_ifs="$IFS" el
  IFS=':'
  for el in $list; do
    if [ -d "$el" ]; then printf '%s' "$el"; IFS="$old_ifs"; return 0; fi
  done
  IFS="$old_ifs"
  return 1
}

# ----------------------------------------------------------------------------
# libsodium VRF-fork detection
#
# cardano-crypto-class needs the IntersectMBO/VRF fork of libsodium, which adds
# the `crypto_vrf_*` API on top of upstream libsodium. A machine with STOCK
# libsodium satisfies `pkg-config --exists libsodium` yet lacks those symbols,
# so we must probe for the VRF API specifically -- not just any libsodium.
#
# Strategy (most robust first):
#   1. If libsodium is not visible to pkg-config at all -> definitely no VRF.
#   2. If a C compiler is available, COMPILE + LINK a tiny probe that calls
#      crypto_vrf_publickeybytes(). Success => VRF fork present.
#   3. If no compiler, fall back to looking for the `crypto_vrf.h` header in the
#      pkg-config includedir as a secondary signal.
#   4. If still unknown, report "no VRF" so the caller installs the fork
#      (installing is safer than wrongly skipping).
libsodium_has_vrf() {
  pkg-config --exists libsodium 2>/dev/null || return 1

  local cc="${CC:-cc}"
  if have "$cc" || have cc; then
    have "$cc" || cc="cc"
    local probe_dir probe_c probe_bin
    probe_dir="$(mktemp -d "${TMPDIR:-/tmp}/plu-stan-vrf-probe.XXXXXX")" || return 1
    probe_c="$probe_dir/probe.c"
    probe_bin="$probe_dir/probe"
    cat > "$probe_c" <<'EOF'
#include <sodium.h>
int main(void){ return (int)crypto_vrf_publickeybytes(); }
EOF
    local cflags libs rc
    cflags="$(pkg-config --cflags libsodium 2>/dev/null)"
    libs="$(pkg-config --libs libsodium 2>/dev/null)"
    if "$cc" $cflags "$probe_c" $libs -o "$probe_bin" >/dev/null 2>&1; then
      rc=0
    else
      rc=1
    fi
    rm -rf "$probe_dir"
    return "$rc"
  fi

  # No compiler available: fall back to a header-presence heuristic.
  local incdir
  incdir="$(pkg-config --variable=includedir libsodium 2>/dev/null)"
  if [ -n "$incdir" ] && [ -f "$incdir/sodium/crypto_vrf.h" ]; then
    return 0
  fi
  if [ -n "$incdir" ] && [ -f "$incdir/crypto_vrf.h" ]; then
    return 0
  fi

  # Unknown: report "no VRF" so the caller installs the fork (safer).
  return 1
}

# Number of parallel jobs for make.
if have nproc; then
  JOBS="$(nproc)"
elif have sysctl; then
  JOBS="$(sysctl -n hw.ncpu 2>/dev/null || echo 2)"
else
  JOBS=2
fi

# ----------------------------------------------------------------------------
# OS / arch detection
# ----------------------------------------------------------------------------
OS="$(uname -s)"
ARCH="$(uname -m)"
BREW_PREFIX=""

case "$OS" in
  Darwin)
    PLATFORM="macos"
    # Apple Silicon uses /opt/homebrew, Intel uses /usr/local.
    if [ "$ARCH" = "arm64" ]; then
      BREW_PREFIX="/opt/homebrew"
    else
      BREW_PREFIX="/usr/local"
    fi
    ;;
  Linux)
    PLATFORM="linux"
    ;;
  *)
    die "Unsupported operating system: $OS (this script supports macOS and Linux)."
    ;;
esac

say "Detected platform: $PLATFORM ($OS / $ARCH)"
say "Install prefix:     $PREFIX"
say "Build workdir:      $WORKDIR"

# Make sure pkg-config can see what we install (needed for the idempotency
# checks below when $PREFIX/lib/pkgconfig is not already on the default path).
export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"

# ----------------------------------------------------------------------------
# Build prerequisites
# ----------------------------------------------------------------------------
install_prereqs_linux() {
  say "Installing build prerequisites (Linux)"
  if have apt-get; then
    maybe_sudo apt-get update
    maybe_sudo apt-get install -y \
      build-essential automake autoconf libtool pkg-config cmake git curl
  elif have dnf; then
    maybe_sudo dnf install -y \
      gcc gcc-c++ make automake autoconf libtool pkgconfig cmake git curl
  elif have pacman; then
    maybe_sudo pacman -Sy --needed --noconfirm \
      base-devel automake autoconf libtool pkgconf cmake git curl
  else
    warn "Could not detect apt-get, dnf or pacman."
    warn "Please install manually: a C/C++ toolchain, automake, autoconf,"
    warn "libtool, pkg-config, cmake, git and curl, then re-run this script."
  fi
}

install_prereqs_macos() {
  say "Installing build prerequisites (macOS)"

  # Xcode Command Line Tools provide the compiler toolchain.
  if ! xcode-select -p >/dev/null 2>&1; then
    warn "Xcode Command Line Tools are not installed."
    warn "Install them with:  xcode-select --install"
    warn "Then re-run this script."
    die  "Missing Xcode Command Line Tools."
  fi
  info "Xcode Command Line Tools: $(xcode-select -p)"

  if have brew; then
    brew install autoconf automake libtool pkg-config cmake
  else
    warn "Homebrew ('brew') was not found."
    warn "Install it from https://brew.sh and then run:"
    warn "    brew install autoconf automake libtool pkg-config cmake"
    warn "Continuing, but the builds below will fail without these tools."
  fi
}

install_prereqs() {
  case "$PLATFORM" in
    linux) install_prereqs_linux ;;
    macos) install_prereqs_macos ;;
  esac
}

# ----------------------------------------------------------------------------
# Library builders
# ----------------------------------------------------------------------------

# Clone a pinned ref into $WORKDIR/<name>. Uses a shallow clone when the ref
# is a tag/branch; falls back to a full clone + checkout for raw commit SHAs.
clone_ref() {
  local repo="$1" ref="$2" dest="$3"
  rm -rf "$dest"
  if git clone --depth 1 --branch "$ref" "$repo" "$dest" >/dev/null 2>&1; then
    info "Shallow-cloned $repo @ $ref"
  else
    info "Ref '$ref' is not a tag/branch; doing a full clone + checkout."
    git clone "$repo" "$dest"
    git -C "$dest" checkout "$ref"
  fi
}

build_libsodium() {
  if libsodium_has_vrf; then
    say "libsodium (VRF fork) already present ($(pkg-config --modversion libsodium)); skipping."
    return 0
  fi
  if pkg-config --exists libsodium 2>/dev/null; then
    warn "libsodium $(pkg-config --modversion libsodium) is present but lacks the"
    warn "crypto_vrf_* API (stock libsodium, not the IntersectMBO VRF fork)."
    warn "Installing the VRF fork into $PREFIX."
  fi
  say "Building libsodium (VRF fork @ ${LIBSODIUM_REF})"
  local dir="$WORKDIR/libsodium"
  clone_ref "$LIBSODIUM_REPO" "$LIBSODIUM_REF" "$dir"
  (
    cd "$dir"
    ./autogen.sh -s
    ./configure --prefix="$PREFIX"
    make -j"$JOBS"
    maybe_sudo make install
  )
  say "libsodium installed."
}

build_secp256k1() {
  if pkg-config --exists libsecp256k1; then
    say "libsecp256k1 already present ($(pkg-config --modversion libsecp256k1)); skipping."
    return 0
  fi
  say "Building secp256k1 (@ ${SECP256K1_REF}, schnorrsig enabled)"
  local dir="$WORKDIR/secp256k1"
  clone_ref "$SECP256K1_REPO" "$SECP256K1_REF" "$dir"
  (
    cd "$dir"
    if [ -x ./autogen.sh ]; then
      ./autogen.sh
    else
      die "secp256k1: expected ./autogen.sh (autotools build) but none found."
    fi
    ./configure --prefix="$PREFIX" \
      --enable-module-schnorrsig \
      --enable-experimental
    make -j"$JOBS"
    maybe_sudo make install
  )
  say "secp256k1 installed."
}

build_blst() {
  if pkg-config --exists libblst; then
    say "libblst already present ($(pkg-config --modversion libblst)); skipping."
    return 0
  fi
  say "Building blst (@ ${BLST_REF})"
  local dir="$WORKDIR/blst"
  clone_ref "$BLST_REPO" "$BLST_REF" "$dir"
  (
    cd "$dir"
    ./build.sh

    # blst has no `make install`; install the artefacts by hand.
    maybe_sudo mkdir -p "$PREFIX/lib" "$PREFIX/include" "$PREFIX/lib/pkgconfig"
    maybe_sudo cp libblst.a "$PREFIX/lib/"
    maybe_sudo cp bindings/blst.h bindings/blst_aux.h "$PREFIX/include/"

    # Write the pkg-config file so `pkg-config --exists libblst` succeeds.
    local pc="$WORKDIR/libblst.pc"
    cat > "$pc" <<EOF
prefix=${PREFIX}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: libblst
Description: blst BLS12-381 signature library
URL: https://github.com/supranational/blst
Version: ${BLST_VERSION}
Cflags: -I\${includedir}
Libs: -L\${libdir} -lblst
EOF
    maybe_sudo cp "$pc" "$PREFIX/lib/pkgconfig/libblst.pc"
  )
  say "blst installed."
}

# ----------------------------------------------------------------------------
# Discoverability reconciliation
#
# We install the .pc files into $PREFIX/lib/pkgconfig, but on many Linux distros
# that directory is NOT on pkg-config's DEFAULT search path -- so a plain
# `cabal build all` (with no PKG_CONFIG_PATH set) fails with e.g.
#   "pkg-config package libblst-any, not found".
#
# To fix this without duplicating files, we symlink the installed .pc files into
# the first default pkg-config directory (typically /usr/lib/pkgconfig). The .pc
# files contain absolute prefix=... paths, so a symlink from another dir is
# self-consistent. This runs on BOTH platforms and always reconciles (it is not
# gated behind whether a build actually happened this run).
# ----------------------------------------------------------------------------
ensure_pc_discoverable() {
  say "Ensuring installed pkg-config files are on the default search path"

  local default_pc_path target_dir pc linked_any=0
  default_pc_path="$(pkg-config --variable pc_path pkg-config 2>/dev/null || true)"

  if [ -z "$default_pc_path" ]; then
    warn "Could not determine pkg-config's default search path (pc_path); skipping."
    warn "Export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig before building instead."
    return 0
  fi

  # Already on the default path? (macOS/brew, custom prefixes on the path, ...)
  if path_contains "${PREFIX}/lib/pkgconfig" "$default_pc_path"; then
    info "${PREFIX}/lib/pkgconfig is already on pkg-config's default search path; nothing to do."
    return 0
  fi

  # Pick the target default dir: first existing entry, else create the first one.
  if ! target_dir="$(first_existing_dir "$default_pc_path")"; then
    target_dir="${default_pc_path%%:*}"
    info "No default pkg-config dir exists yet; creating $target_dir"
    maybe_sudo mkdir -p "$target_dir"
  fi

  for pc in libsodium.pc libsecp256k1.pc libblst.pc; do
    if [ -f "${PREFIX}/lib/pkgconfig/$pc" ]; then
      maybe_sudo ln -sf "${PREFIX}/lib/pkgconfig/$pc" "$target_dir/$pc"
      info "Linked $target_dir/$pc -> ${PREFIX}/lib/pkgconfig/$pc"
      linked_any=1
    fi
  done

  if [ "$linked_any" -eq 0 ]; then
    warn "No .pc files found in ${PREFIX}/lib/pkgconfig to link."
  else
    say "pkg-config files are now discoverable by cabal via $target_dir."
  fi
}

# ----------------------------------------------------------------------------
# Verification
# ----------------------------------------------------------------------------
# Report install + discoverability status for all three libraries.
#
# Per library we distinguish two notions:
#   * INSTALLED:            found via the seeded $PREFIX/lib/pkgconfig path.
#   * DISCOVERABLE BY CABAL: found with PKG_CONFIG_PATH UNSET, i.e. exactly what
#                            a plain `cabal build all` sees.
#
# Sets the global REPORT_FAIL=1 if ANY library is missing OR installed but not
# discoverable by cabal. Does NOT install or symlink anything (safe for --check).
REPORT_FAIL=0
report_libs() {
  REPORT_FAIL=0
  local lib installed discoverable

  # --- libsodium (must be the VRF fork, not stock libsodium) ---------------
  local sodium_installed=0 sodium_discoverable=0
  if libsodium_has_vrf; then sodium_installed=1; fi
  # Discoverable = VRF fork resolvable with the DEFAULT environment.
  if ( unset PKG_CONFIG_PATH; libsodium_has_vrf ); then sodium_discoverable=1; fi

  if [ "$sodium_installed" -eq 1 ] && [ "$sodium_discoverable" -eq 1 ]; then
    info "OK   libsodium (VRF fork) $(pkg-config --modversion libsodium)  (installed, discoverable)"
  elif [ "$sodium_installed" -eq 1 ]; then
    warn "WARN libsodium (VRF fork) installed in ${PREFIX} but NOT discoverable by cabal"
    warn "     -> run 'make system-deps' to link it onto the default pkg-config path"
    warn "        (or export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig)"
    REPORT_FAIL=1
  elif pkg-config --exists libsodium 2>/dev/null; then
    warn "WARN libsodium $(pkg-config --modversion libsodium) present but WITHOUT the VRF API"
    warn "     (crypto_vrf_*): stock libsodium, not the IntersectMBO VRF fork -> needs install"
    REPORT_FAIL=1
  else
    warn "MISSING libsodium (VRF fork) -> needs install"
    REPORT_FAIL=1
  fi

  # --- secp256k1 + blst ----------------------------------------------------
  for lib in libsecp256k1 libblst; do
    installed=0; discoverable=0
    if pkg-config --exists "$lib" 2>/dev/null; then installed=1; fi
    if env -u PKG_CONFIG_PATH pkg-config --exists "$lib" 2>/dev/null; then discoverable=1; fi

    if [ "$installed" -eq 1 ] && [ "$discoverable" -eq 1 ]; then
      info "OK   $lib $(pkg-config --modversion "$lib")  (installed, discoverable)"
    elif [ "$installed" -eq 1 ]; then
      warn "WARN $lib installed in ${PREFIX} but NOT discoverable by cabal"
      warn "     -> run 'make system-deps' to link it onto the default pkg-config path"
      warn "        (or export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig)"
      REPORT_FAIL=1
    else
      warn "MISSING $lib -> needs install"
      REPORT_FAIL=1
    fi
  done
}

verify() {
  say "Verifying installed libraries"
  report_libs
  [ "$REPORT_FAIL" -eq 0 ] || \
    die "One or more libraries are missing or not discoverable by cabal (see above)."
}

# ----------------------------------------------------------------------------
# Check-only mode (no install, no sudo, no network)
#
# Reports on the current state of the three libraries -- including whether the
# visible libsodium is the VRF fork AND whether each is discoverable by a plain
# `cabal build all` -- and exits nonzero if anything is missing or installed but
# not discoverable. Never installs or symlinks. Used by `make system-deps-check`.
# ----------------------------------------------------------------------------
check_only() {
  say "Checking native libraries (no install, no sudo)"
  report_libs
  if [ "$REPORT_FAIL" -ne 0 ]; then
    die "One or more native libraries are missing or not discoverable by cabal. Run: make system-deps"
  fi
  say "All native dependencies are present and discoverable by cabal."
}

# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------
main() {
  mkdir -p "$WORKDIR"

  install_prereqs

  build_libsodium
  build_secp256k1
  build_blst

  # Always reconcile discoverability, even if every lib was already installed
  # (i.e. no build ran this invocation): the .pc files may still be sitting in
  # $PREFIX/lib/pkgconfig, off pkg-config's default search path.
  ensure_pc_discoverable

  if [ "$PLATFORM" = "linux" ]; then
    # Make sure the runtime linker can find the shared libs in $PREFIX/lib.
    if [ -d /etc/ld.so.conf.d ] && \
       [ "${PREFIX}/lib" != "/usr/lib" ] && [ "${PREFIX}/lib" != "/lib" ]; then
      local conf="/etc/ld.so.conf.d/plu-stan-syslibs.conf"
      printf '%s\n' "${PREFIX}/lib" | maybe_sudo tee "$conf" >/dev/null
      info "Registered ${PREFIX}/lib with the dynamic linker via $conf"
    fi
    say "Refreshing the dynamic linker cache (ldconfig)"
    maybe_sudo ldconfig || warn "ldconfig failed (non-fatal)."
  fi

  verify

  # Clean up the temp build dir only on success.
  rm -rf "$WORKDIR"

  cat <<EOF

$(say "All native dependencies are installed.")

If pkg-config still cannot find them in a fresh shell, make sure the pkg-config
search path includes ${PREFIX}/lib/pkgconfig, e.g.:

    export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:\${PKG_CONFIG_PATH:-}"

Next step:

    cabal build all

EOF
}

case "${1:-}" in
  --check|-c)
    check_only
    ;;
  -h|--help)
    cat <<EOF
Usage: bash scripts/install-system-deps.sh [--check]

  (no args)   Install libsodium (VRF fork), secp256k1 and blst into \$PREFIX.
  --check     Only check whether the libraries are present and correct
              (no install, no sudo, no network). Exits nonzero if any are
              missing or if libsodium lacks the VRF (crypto_vrf_*) API.
EOF
    ;;
  "")
    main "$@"
    ;;
  *)
    die "Unknown argument: $1 (try --check or --help)"
    ;;
esac
